language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t sivalka/docker-kubernetes -f Dockerfile.dev .

script:
  - docker run -e CI=true sivalka/docker-kubernetes npm run test